### ISSUE TITLE
mac universal binary

### ISSUE THREAD

**Issue by frgazor** [ntadej/Vremenar#3]
Is mac universal binary or special build for M1 machines possible? 

Fantastic app btw. I'm using it on linux and mac.

**Comment by ntadej** [comment]
It is coming, but unfortunately not soon as maps engine may need a bit more work.

**Comment by ntadej** [comment]
@frgazor, if you are interested in testing M1 builds, send me an email with your Apple ID and I can add you to the testers list.

**Comment by ntadej** [comment]
This has been available for a while
